### ISSUE TITLE
distance.pdist() fails when metric == 'minkowski'

### ISSUE THREAD

**Issue by xiaobena** [pyannote/pyannote-core#20]
Hi,
I ran into an error when using pyannote.core.utils.distance.pdist. I would appreciate any thoughts about whether I'm up against a bug, or this is unsupported usage.

Reproducing code example:
```python
from pyannote.core.utils import distance
import numpy as np
a  = np.array([[1,2,3], [4,5,6], [7,8,9]])
dis = distance.pdist(arr, metric='minkowski', w=None)
```

Error message:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\scipy\lib\site-packages\pyannote\core\utils\distance.py", line 133, in pdist
    return scipy.spatial.distance.pdist(fX, metric=metric, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\scipy\lib\site-packages\scipy\spatial\distance.py", line 1734, in pdist
    dm = pdist(X, _TEST_METRICS[mstr], **kwargs)
  File "C:\ProgramData\Anaconda3\envs\scipy\lib\site-packages\scipy\spatial\distance.py", line 1690, in pdist
    dm[k] = metric(X[i], X[j], **kwargs)
  File "C:\ProgramData\Anaconda3\envs\scipy\lib\site-packages\scipy\spatial\distance.py", line 481, in minkowski
    dist = norm(u_v, ord=p)
  File "C:\ProgramData\Anaconda3\envs\scipy\lib\site-packages\scipy\linalg\misc.py", line 129, in norm
    a = np.asarray_chkfinite(a)
```

version information:
Python 3.6.8 
NumPy 1.15.0
SciPy 1.0.0

**Comment by hbredin** [comment]
I cannot reproduce this error with `NumPy` 1.14.3` and `SciPy` 1.1.0. 

```python
>>> from pyannote.core.utils import distance
>>> import numpy as np
>>> a  = np.array([[1,2,3], [4,5,6], [7,8,9]])
>>> distance.pdist(a, metric='minkowski', w=None)  # <== you used arr instead of a
array([ 5.19615242, 10.39230485,  5.19615242])
```

**Comment by xiaobena** [comment]
I updated scipy to 1.1.0 and did not run into the error.

I find a scipy issue https://github.com/scipy/scipy/issues/8142, maybe related?
